# -*- coding: utf-8 -*-
"""Untitled35.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i8-JoKnPK_67YAMWyo-EVuorQsD9ECRH
"""

from skimage.segmentation import watershed
import numpy as np
import cv2
from copy import deepcopy


def watershed_segmentation(gray_img, k = 13):
  if gray_img.shape[2] == 3:  # check if image is RGB
    gray_img = cv2.cvtColor(gray_img, cv2.COLOR_BGR2GRAY)
  blur = cv2.medianBlur(gray_img, ksize = k)
  wshed = watershed(255 - blur, watershed_line = True)
  return wshed